version: "3.9"
services:
  frontend:
    container_name: portfolio_frontend
    build:
      context: .
      target: frontend
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    ports:
      - 4001:3000
    environment:
      - PRODUCTION=false
  backend:
    container_name: portfolio_backend
    build:
      context: .
      target: backend
    volumes:
      - ./backend/index.js:/app/index.js
      - ./backend/src:/app/src
      - ./backend/db:/app/db
    ports:
      - 3010:3010
